# Generated by Django 5.1.3 on 2024-11-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_payment_amount_alter_payment_date_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthlog', to='members.member'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='members.member'),
        ),
    ]
